spring:
  application:
    name: admin-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.60.16:8848
        namespace: d3327922-b26c-49a3-aea0-99283904130b
  boot: # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
  security: # 配置登录用户名和密码
    user:
      name: admin
      password: admin
server:
  port: 9301