spring:
  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:oracle:thin:@192.168.5.70:1521:pep
    username: baseinfonew
    password: abc1234

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml